version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: molenaar-postgres
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d molenaar"]
      interval: 10s
      timeout: 5s
      retries: 5