spring:
  main:
    web-application-type: REACTIVE
  datasource:
    url: jdbc:postgresql://10.10.3.110:5432/molenaar
    username: postgres
    password: postgres
quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    reactive:
      url: postgresql://10.10.3.110:5432/molenaar
      max-size: 20
hibernate:
  database:
    generation: drop-and-create
  reactive:
    enabled: true
    sql-load-script: no-file
    dialect: org.hibernate.dialect.PostgreSQLDialect
