name: Dependency Check

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'gradle'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run OWASP Dependency Check
        run: ./gradlew dependencyCheckAnalyze
